function(add_sources_to_project)
    set(oneValueArgs TARGET)
    set(multiValueArgs SOURCES)
    cmake_parse_arguments(ARG "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    list(TRANSFORM ARG_SOURCES PREPEND ${CMAKE_CURRENT_SOURCE_DIR}/)
    message("Adding SOURCES")
    foreach(SRC_FILE ${ARG_SOURCES})
        message("\t" ${SRC_FILE})
    endforeach()
    message("To TARGET=" ${ARG_TARGET})
    target_sources(${ARG_TARGET} PRIVATE ${ARG_SOURCES})
endfunction(add_sources_to_project)
